name: Maven Publish

on:
  workflow_dispatch:
    inputs:
      java-version:
        description: "Java version for Maven publishing"
        type: string
        default: "25"
      version:
        description: "The Maven version to publish, e.g. 1.1.1-rc1"
        type: string
        required: true
      tag-name:
        description: "The GitHub release tag name"
        type: string
        required: true
      hytale-server-version:
        description: "The Hytale Server version to use for dependency resolution"
        type: string
        required: true

permissions:
  contents: read

jobs:
  maven-publish:
    uses: nitrado/hytale-plugin-workflows/.github/workflows/maven-publish.yml@v2
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version }}
      version: ${{ inputs.version }}
      tag-name: ${{ inputs.tag-name }}
      hytale-server-version: ${{ inputs.hytale-server-version }}

